version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123

    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
